# Generated by Django 4.0.4 on 2022-05-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'GET'), (2, 'POST'), (3, 'PUT'), (4, 'DELETE'), (5, 'PATCH')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BaseInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=500, unique=True)),
                ('hompage', models.CharField(max_length=500, unique=True)),
                ('signin', models.CharField(max_length=500, unique=True)),
                ('singup', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'verbose_name': 'Base Information',
            },
        ),
        migrations.CreateModel(
            name='FormDetailsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=250, unique=True)),
                ('page_link', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=250)),
                ('is_auth_related', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Form Detials Iteam',
            },
        ),
        migrations.CreateModel(
            name='FormItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_link', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.CharField(max_length=250)),
                ('type', models.CharField(blank=True, max_length=250)),
                ('is_auth_related', models.BooleanField(default=False)),
                ('tag', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Form Iteam',
            },
        ),
        migrations.CreateModel(
            name='LinkActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500, unique=True)),
                ('orginal_param', models.TextField(blank=True, null=True)),
                ('orginal_page', models.TextField(blank=True, null=True)),
                ('manupulated_param', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Link Action Iteam',
            },
        ),
        migrations.CreateModel(
            name='LinkActionItemPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500, unique=True)),
                ('orginal_param', models.TextField(blank=True, null=True)),
                ('orginal_page', models.TextField(blank=True, null=True)),
                ('manupulated_param', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Link Action Iteam',
            },
        ),
        migrations.CreateModel(
            name='LinkActionItemResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('is_idor', models.BooleanField(default=True)),
                ('action_link', models.CharField(blank=True, max_length=500, null=True)),
                ('effected_full_page', models.TextField(blank=True, null=True)),
                ('tag', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Link Action Item Response',
            },
        ),
        migrations.CreateModel(
            name='LinkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_link', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.CharField(max_length=500, unique=True)),
                ('tag', models.CharField(blank=True, max_length=150, null=True)),
                ('link_location', models.CharField(max_length=250)),
                ('link_location_method', models.CharField(max_length=250)),
                ('obj', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Link Iteam',
            },
        ),
        migrations.CreateModel(
            name='LoggedInUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500, unique=True)),
                ('user_id', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'verbose_name': 'Logged In User Information',
            },
        ),
        migrations.CreateModel(
            name='LinkAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500, unique=True)),
                ('is_loggedin', models.CharField(blank=True, max_length=150, null=True)),
                ('full_page', models.TextField(blank=True, null=True)),
                ('started_time', models.DateField(auto_now_add=True)),
                ('completed_time', models.DateField(auto_now_add=True)),
                ('action_type', models.ManyToManyField(default=1, to='core.actions')),
            ],
            options={
                'verbose_name': 'Link Action',
            },
        ),
    ]
