# Generated by Django 3.2.10 on 2022-03-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('tag', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Link Iteam',
            },
        ),
    ]
