# Generated by Django 4.0.4 on 2022-05-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkactionitempost',
            options={'verbose_name': 'Link Action Iteam post'},
        ),
    ]
