# Generated by Django 3.2.10 on 2022-03-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkitem',
            name='link',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
