# Generated by Django 3.2.10 on 2022-03-11 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_linkitem_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'GET'), (2, 'POST'), (3, 'PUT'), (4, 'DELETE'), (5, 'PATCH')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FormDetailsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('is_auth_related', models.BooleanField(default=False)),
                ('input1', models.CharField(blank=True, max_length=250)),
                ('input2', models.CharField(blank=True, max_length=250)),
                ('input3', models.CharField(blank=True, max_length=250)),
                ('input4', models.CharField(blank=True, max_length=250)),
                ('input5', models.CharField(blank=True, max_length=250)),
                ('input6', models.CharField(blank=True, max_length=250)),
                ('input7', models.CharField(blank=True, max_length=250)),
                ('input8', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'Form Detials Iteam',
            },
        ),
        migrations.CreateModel(
            name='FormItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=250)),
                ('type', models.CharField(blank=True, max_length=250)),
                ('is_auth_related', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Form Iteam',
            },
        ),
        migrations.CreateModel(
            name='LinkActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500, unique=True)),
                ('type', models.ManyToManyField(to='core.Actions')),
            ],
            options={
                'verbose_name': 'Link Action Iteam',
            },
        ),
        migrations.CreateModel(
            name='LinkActionItemResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.linkactionitem')),
            ],
            options={
                'verbose_name': 'Link Action Iteam Response',
            },
        ),
    ]
