# Generated by Django 3.2.10 on 2022-03-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_actions_formdetailsitem_formitem_linkactionitem_linkactionitemresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdetailsitem',
            name='input1',
        ),
        migrations.RemoveField(
            model_name='formdetailsitem',
            name='input2',
        ),
        migrations.RemoveField(
            model_name='formdetailsitem',
            name='input3',
        ),
        migrations.RemoveField(
            model_name='formdetailsitem',
            name='input4',
        ),
        migrations.RemoveField(
            model_name='formdetailsitem',
            name='input5',
        ),
        migrations.RemoveField(
            model_name='formdetailsitem',
            name='input6',
        ),
        migrations.RemoveField(
            model_name='formdetailsitem',
            name='input7',
        ),
        migrations.RemoveField(
            model_name='formdetailsitem',
            name='input8',
        ),
        migrations.AddField(
            model_name='formdetailsitem',
            name='page_link',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
