# Generated by Django 3.2.10 on 2022-03-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220312_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdetailsitem',
            name='link',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
