# Generated by Django 3.2.10 on 2022-03-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_formdetailsitem_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=500, unique=True)),
                ('hompage', models.CharField(max_length=500, unique=True)),
                ('signin', models.CharField(max_length=500, unique=True)),
                ('singup', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'verbose_name': 'Base Information',
            },
        ),
    ]
