# Generated by Django 3.2.10 on 2022-03-24 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_baseinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectedLinkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_link', models.CharField(max_length=500, unique=True)),
                ('obj', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Link Iteam',
            },
        ),
        migrations.RemoveField(
            model_name='linkactionitem',
            name='type',
        ),
        migrations.AddField(
            model_name='formitem',
            name='tag',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='linkactionitem',
            name='action_type',
            field=models.ManyToManyField(default=1, to='core.Actions'),
        ),
        migrations.AddField(
            model_name='linkactionitem',
            name='completed_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkactionitem',
            name='full_page',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkactionitem',
            name='is_loggedin',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='linkactionitem',
            name='started_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkactionitemresponse',
            name='full_page',
            field=models.TextField(blank=True, null=True),
        ),
    ]
