# Generated by Django 3.2.10 on 2022-03-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220324_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkitem',
            name='link_location',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkitem',
            name='link_location_method',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
