# Generated by Django 3.2.10 on 2022-03-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220324_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkactionitemresponse',
            old_name='full_page',
            new_name='effected_full_page',
        ),
        migrations.AddField(
            model_name='linkactionitem',
            name='manupulated_param',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkactionitem',
            name='orginal_param',
            field=models.TextField(blank=True, null=True),
        ),
    ]
