# Generated by Django 3.2.10 on 2022-04-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220325_1259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ObjectedLinkItem',
        ),
        migrations.AddField(
            model_name='linkitem',
            name='obj',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
