# Generated by Django 3.2.10 on 2022-04-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220414_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkactionitem',
            name='completed_time',
        ),
        migrations.RemoveField(
            model_name='linkactionitem',
            name='full_page',
        ),
        migrations.RemoveField(
            model_name='linkactionitem',
            name='is_loggedin',
        ),
        migrations.RemoveField(
            model_name='linkactionitem',
            name='started_time',
        ),
        migrations.CreateModel(
            name='LinkAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500, unique=True)),
                ('is_loggedin', models.CharField(blank=True, max_length=150, null=True)),
                ('full_page', models.TextField(blank=True, null=True)),
                ('started_time', models.DateField(auto_now_add=True)),
                ('completed_time', models.DateField(auto_now_add=True)),
                ('action_type', models.ManyToManyField(default=1, to='core.Actions')),
            ],
            options={
                'verbose_name': 'Link Action',
            },
        ),
    ]
