# Generated by Django 3.2.10 on 2022-04-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220414_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkactionitem',
            name='action_type',
        ),
    ]
